# Generated by Django 5.1.1 on 2024-09-03 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='нет названия товара', help_text='Укажите название товара', max_length=150, verbose_name='название товара')),
                ('price', models.PositiveIntegerField(default=0, help_text='Укажите цену товара', verbose_name='цена товара')),
                ('description', models.TextField(default='нет описания товара', help_text='Введите описание товара', max_length=400, verbose_name='описание товара')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фото товара', null=True, upload_to='ads/', verbose_name='фото товара')),
                ('created_at', models.DateField(verbose_name=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания'))),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст отзыва', max_length=400, verbose_name='текст отзыва')),
                ('created_at', models.DateField(verbose_name=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время создания'))),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ('-created_at',),
            },
        ),
    ]
